baseURL: "https://nanotheprogrammer.github.io/" 
title: Kumarmangalam Patravali
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: My life so far
          url: data/
          weight: 3 
        - name: Newsletter
          url: https://pmichaillat.substack.com
          weight: 4

params:
    description: "I am a Professor of Subject at the University of Place. My research covers various topics.
consequat."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Kumarmangalam Patravali
          subtitle: "I am studying (and researching on) History of Mathematics and Physics. Apart from that, I am always somewhere near good food, Mediterranian wine & women, logic & semantics and pure mathematics."
          imageUrl: "zoomed.jpeg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Me on the island of Skiathos
          buttons:
            - name: Papers
              url: papers/
            - name: Courses taken
              url: courses/
            - name: My life so far
              url: data/
            - name: Newsletter
              url: https://kumarmangalam.substack.com
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: lebenslauf_Patravali_standOkt23.pdf
        - name: Email
          url: mailto:kumarmangalamjr@gmail.com
        - name: Location
          url: location/
        - name: Schedule 
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?view_op=list_works&hl=de&user=-anR9ZAAAAAJ
        - name: YouTube
          url: https://www.youtube.com/@ThinklikeThales-pd7sq
        - name: GitHub
          url: https://github.com/nanotheprogrammer
        - name: Substack
          url: https://kumarmangalam.substack.com
        - name: Twitter
          url: https://twitter.com/KumarmangalamP4

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Home"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
